require("conform").setup({
	formatters_by_ft = {
		lua = { "stylua" },
		go = { "goimports", "gofumpt" },
		rust = { "rustfmt" },
		c = { "clang-format" },
		cpp = { "clang-format" },
		javascript = { "prettier" },
		typescript = { "prettier" },
		javascriptreact = { "prettier" },
		typescriptreact = { "prettier" },
		json = { "prettier" },
		jsonc = { "prettier" },
		css = { "prettier" },
		html = { "prettier" },
		yaml = { "prettier" },
		markdown = { "prettier" },
		toml = { "taplo" },
		sh = { "shfmt" },
		bash = { "shfmt" },
		zsh = { "shfmt" },
		python = { "ruff_format", "ruff_organize_imports" },
		sql = { "sql_formatter" },
		asm = { "nasmfmt" },
	},
	formatters = {
		sql_formatter = {
			prepend_args = { "--language", "postgresql", "-c", '{"useTabs":true,"tabWidth":4}' },
		},
		nasmfmt = {
			command = "nasmfmt",
			args = { "-ii", "8", "$FILENAME" },
			stdin = false,
		},
	},
	format_on_save = {
		timeout_ms = 2000,
		lsp_format = "fallback",
	},
})
